#include "ocl_wrapper.h"

static char	*private_ocl_error_to_string1(int error_code)
{
	static char error_strings[][44] = {
	"SUCCESS", "DEVICE NOT FOUND", "DEVICE NOT AVAILABLE",
	"COMPILER NOT AVAILABLE", "MEM OBJECT ALLOCATION FAILURE",
	"OUT OF RESOURCES", "OUT OF HOST MEMORY", "PROFILING INFO NOT AVAILABLE",
	"MEM COPY OVERLAP", "IMAGE FORMAT MISMATCH", "IMAGE FORMAT NOT SUPPORTED",
	"BUILD PROGRAM FAILURE", "MAP FAILURE", "MISALIGNED SUB BUFFER OFFSET",
	"EXEC STATUS ERROR FOR EVENTS IN WAIT LIST", "COMPILE PROGRAM FAILURE",
	"LINKER NOT AVAILABLE", "LINK PROGRAM FAILURE", "DEVICE PARTITION FAILED",
	"KERNEL ARG INFO NOT AVAILABLE", "INVALID VALUE", "INVALID DEVICE TYPE",
	"INVALID PLATFORM", "INVALID DEVICE", "INVALID CONTEXT",
	"INVALID QUEUE PROPERTIES", "INVALID COMMAND QUEUE", "INVALID HOST PTR",
	"INVALID MEM OBJECT", "INVALID IMAGE FORMAT DESCRIPTOR",
	"INVALID IMAGE SIZE", "INVALID SAMPLER", "INVALID BINARY",
	"INVALID BUILD OPTIONS", "INVALID PROGRAM", "INVALID PROGRAM EXECUTABLE",
	"INVALID KERNEL NAME", "INVALID KERNEL DEFINITION", "INVALID KERNEL",
	"INVALID ARG INDEX", "INVALID ARG VALUE", "INVALID ARG SIZE",
	"INVALID KERNEL ARGS", "INVALID WORK DIMENSION", "INVALID WORK GROUP SIZE",
	"INVALID WORK ITEM SIZE", "INVALID GLOBAL OFFSET", "INVALID EVENT WAIT LIST"
	, "INVALID EVENT", "INVALID OPERATION", "INVALID GL OBJECT",
	"INVALID BUFFER SIZE", "INVALID MIP LEVEL", "INVALID GLOBAL WORK SIZE",
	"INVALID PROPERTY", "INVALID IMAGE DESCRIPTOR", "INVALID COMPILER OPTIONS",
	"INVALID LINKER OPTIONS", "INVALID DEVICE PARTITION COUNT"};

	return (error_strings[abs(error_code)]);
}

char		*ocl_error_to_string(int error_code)
{
	char *error_string;

	if (error_code > 0 || error_code < -68)
		return ("UNKNOWN");
	return (private_ocl_error_to_string1(error_code));
}
